apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "docker"
spec:
  title: "Docker fundamentals"
  description: "Learn the fundamentals of Docker"
  url: https://github.com/GlobeTeam-Platform/ga-kursus-docker
  publish:
    image: "$(image_repository)/ga-kursus-docker-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: $(image_repository)/ga-kursus-docker-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      slides:
        enabled: true
      terminal:
        enabled: true
        #layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: true
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: application
      port: 80
    dashboards:
    - name: App
      url: "$(ingress_protocol)://application-$(session_name).$(ingress_domain)/"

